### ISSUE TITLE
Question related to Cross-design

### ISSUE THREAD

**Issue by jeong2624** [JessieChen7/LinSNPGT#1]
I discovered that the CropGS-hub offers a module called Cross-design.
I'm curious about the algorithms used to generate crossbreeding and phenotype prediction. 
Can you provide information on this?

**Comment by JessieChen7** [comment]
For the CrossingDesign module, all training set populations used were hybrid populations of rice and maize. Once users upload the genotypes of rice or maize as parents, the platform will simulate the genotypes of hybrids based on the combinations selected by the user, and then use models on the platform to predict phenotypes of these hybrids. 

Since the genotypes of most inbred lines parents are basically homozygous, most of the genotypes obtained through SNPGT provided by users should also be homozygous (because they are inbred lines). Therefore, if the parental genotypes are different, the F1 individual is set as heterozygous, and if they are the same, the F1 individual is set as homozygous. Of course, there may be a certain proportion of missing or heterozygosity in the genotypes of the inbred line parents. For these sites, F1 is set as missing temporarily, and then Beagle software is used to impute them with the training set. Finally, the F1 genotypes of imputation are then substituted into the GS model for prediction.

**Comment by jeong2624** [comment]
Thank you for answering my question. 
I have additional questions regarding the answer.
So how do you create a combination? 
Do you simply randomly create a matrix from a genotype matrix?

**Comment by JessieChen7** [comment]
There are two combination methods set up in our system. One is to simulate all hybrids that may be obtained after crossing all samples in pairs, that is Cn2; the other is to select one sample and combine it with the remaining other samples to produce hybrids, that is 1 x (n -1). 
We create the genotype matrix of hybrids from parents’ genotypes which is obtained from SNPGT and uploaded by users, the rule of which have been explained above.

**Comment by jeong2624** [comment]
Thank you for the information.

2024년 1월 16일 (화) 오후 3:36, Jiaxin Chen ***@***.***>님이 작성:

**Comment by yunmika** [comment]
Thanks to the authors for developing the platform, I am equally interested in Cross-design. May I ask if I have parents with heterozygous genotypes and also calculated genetic map, may I predict the genotypes of the offspring based on the heterozygous genotypes of the parents and the genetic map, I wonder if this idea is feasible?

**Comment by JessieChen7** [comment]
> Thanks to the authors for developing the platform, I am equally interested in Cross-design. May I ask if I have parents with heterozygous genotypes and also calculated genetic map, may I predict the genotypes of the offspring based on the heterozygous genotypes of the parents and the genetic map, I wonder if this idea is feasible?

Thank you for your interest. This idea is feasible in principle. For heterozygous parents, the parental genotypes should first be phased, and then recombination and gamete transmission can be simulated using the genetic map to generate possible offspring genotypes.
However, the current Cross-design module is mainly designed for highly homozygous rice and maize inbred lines and does not explicitly simulate meiosis or recombination from heterozygous parents.
